apiVersion: apps/v1
kind: Deployment
metadata:
  name: techgame-deployment
spec:
  selector:
    matchLabels:
      app: techgame
  replicas: 2
  template:
    metadata:
      labels:
        app: techgame
    spec:
      containers:
        - name: techgame
          image: latchudevops/techgame:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080


---

apiVersion: v1
kind: Service
metadata:
  name: techgame-ssvc
spec:
  selector:
    app: techgame
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080 
  type: LoadBalancer
